0.0.14

diff --git a/impala-tpcds/tpcds-env.sh.template b/impala-tpcds/tpcds-env.sh.template
--- a/impala-tpcds/tpcds-env.sh.template
+++ b/impala-tpcds/tpcds-env.sh.template
@@ -11,14 +11,20 @@ DSDGEN_THREADS_PER_NODE=12
 TPCDS_DBNAME=tpcds_parquet
 QUERY_TYPE="imp"
 
-DN_COUNTER=$(cat $LOCAL_PWD/dn.txt | wc -l)
-RANDOM_COUNTER=$(( ( RANDOM % $DN_COUNTER )  + 1 ))
-PARALLEL=$(($DN_COUNTER * $DSDGEN_THREADS_PER_NODE))
+if [ -f $LOCAL_PWD/dn.txt ]; then
+	DN_COUNTER=$(cat $LOCAL_PWD/dn.txt | wc -l)
+	RANDOM_COUNTER=$(( ( RANDOM % $DN_COUNTER )  + 1 ))
+	PARALLEL=$(($DN_COUNTER * $DSDGEN_THREADS_PER_NODE))
 
-i="0"
-for dn in $(cat $LOCAL_PWD/dn.txt); do
-	i=$(($i + 1))
-	if [ "$i" -eq "$RANDOM_COUNTER" ]; then
-		IMP_HOST="$dn"
-	fi
-done
+	i="0"
+	for dn in $(cat $LOCAL_PWD/dn.txt); do
+		i=$(($i + 1))
+		if [ "$i" -eq "$RANDOM_COUNTER" ]; then
+			IMP_HOST="$dn"
+		fi
+	done
+else
+	echo "$PWD/dn.txt not found!"
+	echo "Please enter all of the datanodes into this file and try again."
+	exit 1
+fi
